server:
  port: 8080
spring:
  datasource:
    url: jdbc:h2:mem:letter-formatter-service-db
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  thymeleaf:
    suffix: .xml
    encoding: UTF-8
    servlet:
      content-type: text/xml